[SDK-265] Add pxration signal to ORTB request
loopme/ios-united-sdk pull request #128
Opened 2024-06-05 10:28 UTC by ValeriiLoopMe

Here is calculation func  ratio of physical pixels to device independent pixels to setup correct value to `pxration` on Device Object. Tested by CharleProxy 
<img width="512" alt="Screenshot 2024-06-05 at 12 24 30" src="https://github.com/loopme/ios-united-sdk/assets/145434188/828b7bca-ab26-47f3-9322-1381d7d82d31">

2024-06-05 20:18 UTC, bzarzoza commented
Can you show the log from Charles? I'm not able to see if this calculation is accurate with the information provided.

2024-06-06 14:55 UTC, bzarzoza requested changes
Formatting should be done with NSNumberFormatter.

2024-06-06 14:55 UTC, bzarzoza commented on framework/LoopMeUnitedSDK/Core/Internal/Builder/LoopMeORTBTools.m
> +            @"pxratio": @([LoopMeIdentityProvider calculatePxratioOfScreen]),
This needs to be formatted with `NSNumberFormatter`.

// Assuming `LoopMeIdentityProvider` is already imported and calculatePxratioOfScreen is available

float pxratio = [LoopMeIdentityProvider calculatePxratioOfScreen];
NSNumber *pxratioNumber = @(pxratio);

// Create a number formatter
NSNumberFormatter *numberFormatter = [[NSNumberFormatter alloc] init];
[numberFormatter setNumberStyle:NSNumberFormatterDecimalStyle];
[numberFormatter setMinimumFractionDigits:3];
[numberFormatter setMaximumFractionDigits:3];

// Format the number as a string
NSString *formattedPxratio = [numberFormatter stringFromNumber:pxratioNumber];

// Print the formatted string
NSLog(@"Formatted pxratio: %@", formattedPxratio);

2024-06-06 14:57 UTC, bzarzoza commented on framework/LoopMeUnitedSDK/Core/Internal/Utility/LoopMeIdentityProvider.m
> +    CGFloat screenWidth = [[UIScreen mainScreen] bounds].size.width;
I think this calculation is just w/h. This looks like it calculates Pixels per square inch and divides by 1000.

2024-06-14 11:31 UTC, EpanchinE approved these changes

2024-06-14 11:38 UTC, merged