Unit Tests. AdTrackingLinks, AdVerification, AssetLinks, VastSkipOffset
loopme/ios-united-sdk pull request #41
Opened 2024-02-28 07:41 UTC by EpanchinE

2024-02-28 11:22 UTC, ValeriiLoopMe commented on framework/LoopMeUnitedSDK/AdConfiguration/AdConfiguration/VAST/AdTrackingLinks.swift
> +        return lhs.link == rhs.link && lhs.offset == rhs.offset
We can improve this to 
`public static func == (lhs: LinearTracking, rhs: LinearTracking) -> Bool {
    return lhs.allFields() == rhs.allFields()
}`

2024-02-28 15:02 UTC, ValeriiLoopMe requested changes

2024-02-29 06:51 UTC, EpanchinE commented on framework/LoopMeUnitedSDK/AdConfiguration/AdConfigurationTests/AdTrackingLinksTests.swift
> +
Agree

2024-02-29 10:04 UTC, ValeriiLoopMe approved these changes

2024-02-29 11:01 UTC, merged